sudo: required
language: minimal
services:
- docker
script:
- pip install awscli --upgrade --user
- eval $(aws ecr get-login --region us-east-1 --no-include-email)
- docker build -t 234514569215.dkr.ecr.us-east-1.amazonaws.com/simulation-queue:$TRAVIS_BRANCH-$TRAVIS_COMMIT .
deploy:
  provider: script
  script: >-
    docker tag 234514569215.dkr.ecr.us-east-1.amazonaws.com/simulation-queue:$TRAVIS_BRANCH-$TRAVIS_COMMIT 234514569215.dkr.ecr.us-east-1.amazonaws.com/simulation-queue:$TRAVIS_BRANCH &&
    docker push 234514569215.dkr.ecr.us-east-1.amazonaws.com/simulation-queue:$TRAVIS_BRANCH-$TRAVIS_COMMIT &&
    docker push 234514569215.dkr.ecr.us-east-1.amazonaws.com/simulation-queue:$TRAVIS_BRANCH
  if: tag IS present
env:
  global:
  - secure: lhyI1d3uWXgrYKUsPgbt4qAg4Jk8mclWsV+u+NQjmSy/NK1cUlFCRAISMS3E4fj271R5hYLztUGos2T6sXZdBMWt2yNu7bYs2BdiA87qB2WeuHtBXuUGF+aS60oGYfFVR4VvppC7YwOUyHljc3MDexC1ULGegIFcpr7OvxT1XCPoBFY8yCkzyIxfFRtVE8omtx5ammXB149+yarPSc4pcS9zto9Z3Foa52EZjt2u/cX+Iii6UdizgJEMtkqp3q0McZzVHTpEGSFKrOHDOR4Q2pz0qPBFQ+fH0WQCmk2wxJnFNcPndHGAmsVSVs6p6/0OsDOj4DFBxCyWK0xX0XMModKCwb8KfnnNAub9vN+NrohzhIFJ8ca/JGX7q76BI5+sldxIS52HaiBPQF4QzbDHPzwTyPL8cFp3okjt1rqcFzB/bO4Mv6VtbDz8yT6FRUbHY0D/2m7AG3cQmBkiV25gIR3e2bC8U1+6o+HBsONpY7LaFlS92RGQLV7PMwxK1MvaliSqWw3iPOnPgSIiHSA+VrSki1bIwkud8wHJ7QNaB/O+l/Zhod1rM9TsO57OzFbjxJWVTGwYz3XklPzZ8iiqbsiPDvpzq1Jd1kseId5ALH7TemIer3pq8JWqiFKuw9k/u/TjDVf19+FihwWroheSuGW9jGCRXLZyLOJDn1tqpfc=
  - secure: nG2kRGG0r/dvgYAjY8ojODLi1GXXMPAMOS/DK5LFWx3YWwWIGBNEVR6p1IvEZFVE9LOlAGpMtifeKkrjt1TMzXpn3dGWRoj6tb6Pf+dqjLzGGCMTOT5BEJXFjvzjJqWvFXbmQtDhSY+OZbwFn3mTraUgG5ynVEyCFW7dQCSaQmZcV4/8XA3jg4dPQ7RjDIj1wdcNhzNmVgicgbEMbGyXcKXMOtfxfKrhy1YmFXb3250wftjGhRaYiJHMRHZn0Av6iAAMStXcOzcoZlrfbT64+Cokty8lpJreyuJ6MOWIvETXEYztux6M4RhejnoX2V9I+teqJsmwk0VGKchab3f1mlSHr5nhU6nZHskBGZzjCpXpyUeHKGyaJpPbxbKxTexLYqHxCt7sX/j/LMNh5DsQRu+ra0g9gs+5Nom3FqOzEKJGXPN/6impu+5+IKQbU5Ma9kfjXfXQ4lj/zXQl4PF/oROEXCXeMBzBynFoQNGHK43rSpiBa0m9M3dDwEixmxeLvU2/HzAP5GXFLTtTK26RW0kIX3PgImlFRJuiYtJZnnJTiryjd4D2d8KcBLye4iwEmXG1vc28CsSC6cTJz8NpAKHK1NGgY9BFTHRRefXo7cJ6D1E9o4r/gDPLPiBhdWkXHclqt6HyQ2tvehT+saVYc8vbSpLWmIu6xjheFGQLBQc=
